language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.1.4
script:
  - "bundle exec rake lint spec SPEC_OPTS='--format documentation'"
env:
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION="~> 3.0.0"
  - PUPPET_VERSION="~> 3.1.0"
  - PUPPET_VERSION="~> 3.6.0"
  - PUPPET_VERSION="~> 3.8.0"
  - PUPPET_VERSION="~> 4.2"
matrix:
  exclude:
    - rvm: 1.8.7
      env: PUPPET_VERSION="~> 4.2"
    - rvm: 2.1.4
      env: PUPPET_VERSION="~> 2.7.0"
    - rvm: 2.1.4
      env: PUPPET_VERSION="~> 3.0.0"
    - rvm: 2.1.4
      env: PUPPET_VERSION="~> 3.1.0"

gemfile: .gemfile
notifications:
  email:
    - al@lab42.it
